### ISSUE TITLE
Include your repository url in the NuGet package

### ISSUE THREAD

**Issue by carlin-q-scott** [zerobounce/zero-bounce-csharp-sdk-setup#1]
When I searched NuGet for a ZeroBounce package, I saw this one, but I wasn't going to use it because the package had no source code attached to it.

**Comment by aolariusst** [comment]
I've updated the Nuget package, let me know if it fixes your issues
https://www.nuget.org/packages/ZeroBounce.SDK

**Comment by carlin-q-scott** [comment]
@aolariusst It's linking to the php sdk github project.

**Comment by aolariusst** [comment]
> @aolariusst It's linking to the php sdk github project.

@carlin-q-scott good catch; sorry about that; fixed it
